use customer;

SELECT * 
FROM customer_behavior;

-- what is the total revenue  generated by male v/s fremale customer?

SELECT gender, SUM(purchase_amount) AS total_revenue
FROM customer_behavior
GROUP BY gender;

-- which customer used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount, 
(SELECT AVG(purchase_amount) FROM customer_behavior) AS overall_avg_spend
FROM customer_behavior
WHERE discount_applied = 'Yes'
AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_behavior);
  
-- which are the top 5 product with the highest average review rating ?

SELECT item_purchased, ROUND(AVG(review_rating), 2) AS avg_rating
FROM customer_behavior
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- comparing the average purchase amounts between standered and express shipping.

SELECT 
ROUND(AVG(CASE WHEN shipping_type = 'Standard' THEN purchase_amount END), 2) AS standard_avg,
ROUND(AVG(CASE WHEN shipping_type = 'Express' THEN purchase_amount END), 2) AS express_avg,
ROUND(AVG(CASE WHEN shipping_type = 'Express' THEN purchase_amount END) - 
AVG(CASE WHEN shipping_type = 'Standard' THEN purchase_amount END), 2) AS difference
FROM customer_behavior;

/*do subscribed customers spend more? compare average spend and tota revenue 
between subscribers and non-subscribers*/

SELECT subscription_status, COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount), 2) AS avg_spend,
SUM(purchase_amount) AS total_revenue
FROM customer_behavior
GROUP BY subscription_status;

-- whisch five products have the highest percentage of purchase with discount applied ?

SELECT item_purchased, COUNT(*) AS total_orders,
SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_orders,
ROUND((SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0) / COUNT(*), 2)
AS discount_percentage
FROM customer_behavior
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

/*segment customers into new, rating and loyal based on their total numbers of previous purchases, 
and show the count of each segments*/

SELECT CASE WHEN previous_purchases IN (0, 1) THEN 'New'
WHEN previous_purchases IN (2, 3, 4, 5) THEN 'Returning'ELSE 'Loyal'
END AS customer_segment,
COUNT(*) AS customer_count
FROM customer_behavior
GROUP BY 1
ORDER BY customer_count DESC;

-- what are the top 3 most purchased products within each category ?

WITH RankedProducts AS (
SELECT category, item_purchased, COUNT(*) AS total_purchases,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS product_rank
FROM customer_behavior
GROUP BY category, item_purchased)
SELECT category, item_purchased, total_purchases,
product_rank
FROM RankedProducts
WHERE product_rank <= 3
ORDER BY category, product_rank;

-- Are customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT cb.customer_id, cb.subscription_status,
EXISTS (SELECT 1 FROM customer_behavior rb WHERE rb.customer_id = cb.customer_id 
AND rb.previous_purchases > 5) AS is_repeat_buyer
FROM customer_behavior cb;

-- What is the revenue contribution of each age group?

SELECT 
CASE 
WHEN age < 25 THEN 'Under 25'
WHEN age BETWEEN 25 AND 40 THEN '25-40'
WHEN age BETWEEN 41 AND 60 THEN '41-60'
ELSE '60+'
END AS age_group,
COUNT(customer_id) AS total_customers,
SUM(purchase_amount) AS total_revenue,
ROUND((SUM(purchase_amount) * 100.0) / (SELECT SUM(purchase_amount) FROM customer_behavior), 2
    ) AS revenue_contribution_pct
FROM customer_behavior
GROUP BY 1
ORDER BY total_revenue DESC;

select count(*)
from customer_behavior;
